### ISSUE TITLE
gerarLinkAutoLogin

### ISSUE THREAD

**Issue by edilsonlsouza** [ianchamba/whatsapp-whmcs#1]
Olá!

Obrigado pelo modulo, espero que possamos melhorar!

Esta acusando erro nessa função gerarLinkAutoLogin:
Error: Call to undefined function gerarLinkAutoLogin() ...

Obrigado!

**Comment by ianchamba** [comment]
Obrigado pelo feedback, é pq essa função é uma integração que eu faço com o modulo de auto login, vou corrigir para que não tenha esse problema mais caso não for utilizar.

**Comment by ianchamba** [comment]
> Olá!
> 
> Obrigado pelo modulo, espero que possamos melhorar!
> 
> Esta acusando erro nessa função gerarLinkAutoLogin: Error: Call to undefined function gerarLinkAutoLogin() ...
> 
> Obrigado!

Atualizei o código, veja se resolve o seu problema

**Comment by edilsonlsouza** [comment]
Obrigado!

Tudo bem? Se eu tiver meu repositório, para minha solução eu preciso fazer alterações nos arquivos:

https://github.com/edilsonlsouza/zapcel

**Comment by ianchamba** [comment]
Isso mesmo, tem que alterar lá, recomendo utilizar um software para o windows chamado **WinMerge** ele diz exatamente quais linhas foram alteradas de uma versão para outra. 

E por ultimo, o meu modulo tem integração direta com o EvolutionAPI recomendo utilizar essa api, pois eu vi a API que você utiliza e pelo menos por minha experiencia ela é um pouco pesada em relação a outras API, não sei se você paga por ela, mas se for nulled é melhor vc ir para EvolutionAPI que é uma API Open Source e tem atualizações sempre lá.

**Comment by edilsonlsouza** [comment]
Obrigado pelas dicas. Eu tenho um gateway uma API não oficial do WhatsApp, feita em node, eu comprei de uma empresa indiana e fiz diversas melhorias para provedores de internet, como consultar boletos no ERP do provedor, é bem completa.

Eu tenho um servidor dedicado com a API, dar uma olhada no meu site www.hostcel.com.br, se precisar de mim, pode me chamar.

**Comment by ianchamba** [comment]
> Obrigado pelas dicas. Eu tenho um gateway uma API não oficial do WhatsApp, feita em node, eu comprei de uma empresa indiana e fiz diversas melhorias para provedores de internet, como consultar boletos no ERP do provedor, é bem completa.
> 
> Eu tenho um servidor dedicado com a API, dar uma olhada no meu site [www.hostcel.com.br](http://www.hostcel.com.br), se precisar de mim, pode me chamar.

Entendi, eu tenho minha própria API também. Como eu disse, o EvolutionAPI é open source, tem como instalar no servidor dedicado etc. Eu conheço a API que vc utiliza e caso essa empresa indiana não te der atualizações, recomendo sair dela antes que te dê problema, pois a empresa oficial não é indiana, então na verdade a versão que você comprou é uma versão mais barata, uma versão nulled. E o WhatsApp sempre faz atualizações e uma hora sua API pode cair.

Mas se essa empresa indiana lhe oferece atualizações, ai vc tem menos riscos hehe. Eu tenho os arquivos da sua API gratuitamente aqui, já instalei no meu servidor uma vez, mas só não continuei pq não tinha atualizações e eu prefiro ficar em algo que eu tenho certeza que terei atualizações recorrente, entendeu? A API que vc utiliza é muito boa, mas pra mim prefiro algo mais certo.

A API que vc utiliza é o Waziper e o site oficial é https://waziper.com/pricing

**Comment by edilsonlsouza** [comment]
Eu entendo, você tem razão. Eu ainda tenho atualizações, pois eu comprei direto do desenvolvedor, eu não sei ao certo se são indianos, mas me parece devido ao suporte a escritas da direita para esquerda RTL!

Mas quem sabe eu mude em breve, eu não tenho integração apenas com o WHMCS, minha maior é com ERP de provedor de internet, como SGP, IXC Soft.

![image](https://github.com/user-attachments/assets/b087ab24-93bf-473e-a56f-31e5144560b5)

**Comment by edilsonlsouza** [comment]
https://waziper.com/pricing

https://stackposts.com/product/category/main-scripts-1

É o site deles que eles vendem o serviço, eu comprei o código-fonte deles, licenciada para um IP, ai eu faço o que eu quero nos módulos.

**Comment by ianchamba** [comment]
> https://waziper.com/pricing
> 
> https://stackposts.com/product/category/main-scripts-1
> 
> É o site deles que eles vendem o serviço, eu comprei o código-fonte deles, licenciada para um IP, ai eu faço o que eu quero nos módulos.

Ah sim, perfeito, você tem o codigo do desenvolvedor oficial mesmo entao, bem melhor. A plataforma deles é muito boa! Sucesso pra ti!

**Comment by edilsonlsouza** [comment]
Obrigado!

Se precisar de algo, estou a disposição.
